# Generated by Django 4.1.13 on 2024-01-23 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='editar_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('direccion_envio', models.TextField(blank=True, null=True)),
                ('direccion_facturacion', models.TextField(blank=True, null=True)),
                ('nombre_tarjeta', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_tarjeta', models.CharField(blank=True, choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard')], max_length=20, null=True)),
                ('titular_tarjeta', models.CharField(blank=True, max_length=255, null=True)),
                ('caducidad_tarjeta', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
