# Generated by Django 4.1.13 on 2024-01-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_editar_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editar_cliente',
            name='apellidos',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='editar_cliente',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='editar_cliente',
            name='nombre_tarjeta',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='editar_cliente',
            name='titular_tarjeta',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
