# Generated by Django 4.1.13 on 2024-01-23 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_editar_cliente_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editar_cliente',
            options={'verbose_name_plural': 'Datos Clientes'},
        ),
    ]
