# Generated by Django 4.1.13 on 2024-01-23 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0004_alter_editar_cliente_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_envio', models.TextField(blank=True, null=True)),
                ('direccion_facturacion', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='Targeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarjeta', models.CharField(blank=True, max_length=40, null=True)),
                ('tipo_tarjeta', models.CharField(blank=True, choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard')], max_length=20, null=True)),
                ('titular_tarjeta', models.CharField(blank=True, max_length=40, null=True)),
                ('caducidad_tarjeta', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Targetas',
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(max_length=40, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='editar_cliente',
        ),
    ]
