# Generated by Django 4.1.13 on 2024-02-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_alter_comentario_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='valoracion',
            field=models.IntegerField(blank=True, choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], null=True),
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
